# Generated by Django 6.0.6 on 2026-06-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفيلا')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('location', models.CharField(blank=True, max_length=300, null=True, verbose_name='الموقع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'فيلا',
                'verbose_name_plural': 'الفيلات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم التصنيف')),
                ('category_type', models.CharField(choices=[('direct', 'مباشر'), ('indirect', 'غير مباشر')], max_length=10, verbose_name='نوع التصنيف')),
            ],
            options={
                'verbose_name': 'تصنيف مصروف',
                'verbose_name_plural': 'تصنيفات المصروفات',
                'ordering': ['category_type', 'name'],
                'unique_together': {('name', 'category_type')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='رقم المرجع')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('expense_type', models.CharField(choices=[('direct', 'مباشر'), ('indirect', 'غير مباشر')], max_length=10, verbose_name='نوع المصروف')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ الإجمالي')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('supplier_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المورد')),
                ('invoice_image', models.FileField(blank=True, null=True, upload_to='invoices/%Y/%m/', verbose_name='صورة الفاتورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ المخصص')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='expenses.expense', verbose_name='المصروف')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='expenses.villa', verbose_name='الفيلا')),
            ],
            options={
                'verbose_name': 'تخصيص مصروف',
                'verbose_name_plural': 'تخصيصات المصروفات',
                'ordering': ['-expense__date'],
                'unique_together': {('expense', 'villa')},
            },
        ),
    ]
